# 广播机制
两个张量的维度大小向右对齐，触发广播机制的条件：
* a. 同一维度大小相等；
* 或 b. 某个维度 一个张量有，另一个张量没有 ；
* 或 c. 某个维度 一个张量有，另一个张量也有且大小不同，但大小是1。

In [1]:
import torch

In [41]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [3]:
# 矩阵a复制列，矩阵b复制行
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 索引和切片

In [4]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
X[-1], X[1 : 3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [5]:
# 将第2行、第3列的元素改为 9
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
X[0:2, 1:3] = 666
X

tensor([[  0., 666., 666.,   3.],
        [  4., 666., 666.,   7.],
        [  8.,   9.,  10.,  11.]])

# 节省内存

In [15]:
# 如果在后续计算中没有重复使用X， 我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销。
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# zeros_like分配一个全0的块
Z = torch.zeros_like(Y)
print(id(Z))
Z[:] = X + Y
print(id(Z))

1212986128560
1212986128560


# 转换为其他Python对象

In [18]:
# A 与 X 会共享内存
A = X.numpy()
# 该方法针对A创建了新的tensor，不会共享内存
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [23]:
id(A), id(B), id(X)

(1211318144816, 1211317849920, 1211296512816)

In [25]:
# 虽然地址不一样，但X的更新会改变A,但不会改变B
X.add_(1)
X, A, B

(tensor([[  2., 668., 668.,   5.],
         [  6., 668., 668.,   9.],
         [ 10.,  11.,  12.,  13.]]),
 array([[  2., 668., 668.,   5.],
        [  6., 668., 668.,   9.],
        [ 10.,  11.,  12.,  13.]], dtype=float32),
 tensor([[  0., 666., 666.,   3.],
         [  4., 666., 666.,   7.],
         [  8.,   9.,  10.,  11.]]))

In [19]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [40]:
# 练习
a1 = torch.arange(3).reshape((1, 3, 1))
b1 = torch.arange(6).reshape((3, 1, 2))
a1, b1

(tensor([[[0],
          [1],
          [2]]]),
 tensor([[[0, 1]],
 
         [[2, 3]],
 
         [[4, 5]]]))

In [39]:
a1 + b1

RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0