# 入门

In [2]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# 张量的形状
x.shape

torch.Size([12])

In [5]:
# 张量中元素的总数
x.numel()

12

In [6]:
torch.cuda.is_available()

True

In [7]:
# 可以用x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4)
X = x.reshape(3, 4)

In [8]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
# 创建一个形状为（2,3,4）的张量，其中所有元素都设置为0
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
# 创建一个形状为(2,3,4)的张量，其中所有元素都设置为1
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
# 创建一个形状为（3,4）的张量。 其中的每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样
torch.randn(3, 4)

tensor([[-0.8805,  0.2730, -1.0475,  0.4109],
        [-2.0120,  0.6269,  0.9834,  0.2163],
        [-0.6289,  0.1752, -0.3099,  0.5711]])

In [14]:
# 列表创建张量
torch.tensor([[2, 1, 3, 4], [1, 2, 3, 4], [4, 2, 3, 1]])

tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [4, 2, 3, 1]])